FROM node:20-alpine

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true

COPY package.json package-lock.json* ./
RUN npm ci

EXPOSE 3000

CMD ["npm", "run", "dev:docker"]
